### ISSUE TITLE
Issue: URI too long. Duplicates parameters

### ISSUE THREAD

**Issue by Mishasama** [Ephellon/Twitch-Tools#29]
**Describe the bug**

idk.

**To Reproduce**

Please check the screenshot.

**Expected behavior**

You know what to do.

**Screenshots**

![image](https://github.com/user-attachments/assets/ffb5a992-f1ef-41a5-b81d-8521e60a5e52)

**Extension Information**
 - Version: `5.33.4.6/7`
 - Source: `store` & `GitHub`
 - Browser: `chrome` & `edge`
 - Operating System: `Windows`

**Additional comments**

😉

**Comment by Ephellon** [comment]
I know where this error can occur, but I can't reproduce the error without a starting point

**Comment by Ephellon** [comment]
Changed `parseURL...addSearch` to default to overriding parameters. Not sure if this will fix the issue.

**Comment by Mishasama** [comment]
Can we use cookies or local storage instead?

**Comment by Ephellon** [comment]
The URI parameters serve two purposes:

1) Let the extension know it previously failed
2) Force the webpage to reload when told, recollecting resources

----

* Cookies would not be viable, since I'd need to track which tab set what cookie
* `localStorage` is not meant (in this extension) to save logs; [`sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) would be ok until a hard-duplicate is made

**Comment by Ephellon** [comment]
`sessionStorage` would be the best alternative. Will need to rewrite a couple hunder-ish lines?

**Comment by Mishasama** [comment]
> `sessionStorage` would be the best alternative. Will need to rewrite a couple hundred-ish lines?

I'm sorry to have caused you so much trouble.
